from pydantic import Field
from typing import Literal, Annotated, Union, Any
from .basemodel import AmpAVBaseModel
from .av_metadata import AVMetadata
from .transcript import Transcript
from ..logging import ListLoggingHandler, LOG_FORMAT
import logging
from logging import LogRecord

OutputTypes = Annotated[Union[AVMetadata, Transcript], Field(discriminator='ampav_format')]


class ToolOutput(AmpAVBaseModel):
    ampav_format: Literal['tooloutput/1'] = 'tooloutput/1'
    tool_name: str
    tool_version: str | None = Field(None, description="Tool version")
    parameters: dict[str, Any] = Field(default_factory=dict,
                                       description="Tool Parameters")
    queue_time: float | None = Field(None, description="Time the tool was queued")
    start_time: float | None = Field(None, description="Time the tool started")
    end_time: float | None = Field(None, description="Time the tool finished")

    messages: list[str] = Field(default_factory=list, 
                                description="Log messages generated by the tool")
    output: None | OutputTypes = Field(default=None, description="Tool Output")

    def run_duration(self) -> float | None:
        """
        Get the duration of the tool's run, if possible
        
        :return: the run time, or None if it can't be computed
        :rtype: float | None
        """
        if None in (self.start_time, self.end_time):
            return None
        return self.end_time - self.start_time
    

    def queue_duration(self) -> float | None:
        """
        Return the duration of the queue wait if possible
        
        :return: the queue duration or None
        :rtype: float | None
        """
        if None in (self.start_time, self.queue_time):
            return None
        return self.start_time - self.queue_time
    

    def total_duration(self) -> float | None:
        """
        Get the total queue and run duration of the job if possible
        
        :return: The duration or None if it can't be determined
        :rtype: float | None
        """

        r = self.run_duration()
        q = self.queue_duration()
        if q is None:
            return r
        else:
            return None if r is None else r + q


    def setup_logging(self, logger=None, ignore: list[str]=[]):
        """
        Set up logging so log messages to into the messages list
        
        :param logger: optional logger to use for logging
        :param ignore: list of logger prefixes to ignore
        :type ignore: list[str]
        """
        if logger is None:
            logger = logging.getLogger()
        
        def filter(record: LogRecord):
            for p in ignore:
                if p.endswith('.') and record.name.startswith(p):
                    return False
                elif record.name == p:
                    return False            
            return True
            
        formatter = logging.Formatter(LOG_FORMAT)
        handler = ListLoggingHandler(self.messages)
        handler.setFormatter(formatter)
        handler.addFilter(filter)
        logger.addHandler(handler)
        


    


