from pydantic import Field
from typing import Literal, Annotated, Union, Any
from .basemodel import AmpAVBaseModel
from .av_metadata import AVMetadata
from .transcript import Transcript
from ..logging import ListLoggingHandler, LOG_FORMAT
import logging

OutputTypes = Annotated[Union[AVMetadata, Transcript], Field(discriminator='ampav_format')]


class ToolOutput(AmpAVBaseModel):
    ampav_format: Literal['tooloutput'] = 'tooloutput'
    ampav_format_version: Literal[1] = 1
    tool_name: str
    tool_version: str | None = Field(None, description="Tool version")
    parameters: dict[str, Any] = Field(default_factory=dict,
                                       description="Tool Parameters")
    queue_time: float | None = Field(None, description="Time the tool was queued")
    start_time: float | None = Field(None, description="Time the tool started")
    end_time: float | None = Field(None, description="Time the tool finished")

    messages: list[str] = Field(default_factory=list, 
                                description="Log messages generated by the tool")
    output: None | OutputTypes = Field(default=None, description="Tool Output")

    def run_duration(self):
        if None in (self.start_time, self.end_time):
            return None
        return self.end_time - self.start_time
    

    def queue_duration(self):
        if None in (self.start_time, self.queue_time):
            return None
        return self.start_time - self.queue_time
    

    def total_duration(self):
        r = self.run_duration()
        q = self.queue_duration()
        if q is None:
            return r
        else:
            return None if r is None else r + q


    def setup_logging(self, logger=None):
        if logger is None:
            logger = logging.getLogger()
        
        formatter = logging.Formatter(LOG_FORMAT)
        handler = ListLoggingHandler(self.messages)
        handler.setFormatter(formatter)



    


